version: '3.8'

services:
  calcy:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    networks:
      - monitoring 
    environment:
      - GF_SECURITY_ADMIN_USER=ADMIN
      - GF_SECURITY_ADMIN_PASSWORD=ADMIN
    ports:
      - "3001:3000"

networks:
  monitoring:

